# spring.datasource.url=jdbc:h2:mem:hospitaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# spring.datasource.driver-class-name=org.h2.Driver

# spring.datasource.username=sa

# spring.datasource.password=

# spring.jpa.hibernate.ddl-auto=update

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# spring.h2.console.enabled=true

# server.port=8081




##  MYSQL



# spring.datasource.url=jdbc:mysql://localhost:3306/hospitaldb

# spring.datasource.username=root

# spring.datasource.password=root

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update

# spring.jpa.show-sql=true

# server.port=8081


spring.datasource.url=jdbc:postgresql://ep-snowy-dust-aq94m34n-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_6HQ5LYKpnPvg

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=${PORT:8080}